version: '3.5'

services:
  desktop:
    image: consol/centos-xfce-vnc
    networks:
      - atest
    ports:
      - 5901
      - 6901
    dns: 8.8.8.8
networks:
  atest:
    driver: overlay
    attachable: true
