# Custom version actuator
project:
  version: '@project.version@'

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "version, info, health"
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: always
      enabled: true

## Generic application config
audit:
  logDir: c:/var/log/eidas-cidp-proxy
  logFile: audit2.log

event:
  jmsUrl: tcp://eid-systest-admin01.dmz.local:61616
  jmsQueue: logqueue


## Tomcat access log
server:
  port: 8081
  tomcat:
    accesslog:
      directory: c://var/log/eidas-cidp-proxy
      enabled: true
      rotate: false
      pattern: "%h\u0009%l\u0009%u\u0009%t\u0009\u0022%r\u0022\u0009%s\u0009%b\u0009%D\u0009%{no.difi.correlationId}i"
  servlet:
    context-path: /eidas-cidp-proxy

spring:
  resources:
    cache:
      cachecontrol:
        max-age: 31536000
  error:
    whitelabel:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

messages:
  cache:
    seconds: "-1"

dsf:
  gateway:
    url: http://eid-systest-admin01.dmz.local:10009/dsf-gateway/
    connectTimeout: 5000
    readTimeout: 1000

mf:
  gateway:
    url: http://localhost/mf-gateway
    timeout: 5000
    retryCount: 1
