# Custom version actuator
project:
  version: '@project.version@'

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "version, info, health"
  health:
    defaults:
      enabled: false
  endpoint:
    health:
      show-details: always
      enabled: true

## Tomcat access log
server:
  port: 8081
  tomcat:
    accesslog:
      directory: c://var/log/eidas-cidp-proxy
      enabled: true
      rotate: false
      pattern: "%h\u0009%l\u0009%u\u0009%t\u0009\u0022%r\u0022\u0009%s\u0009%b\u0009%D\u0009%{no.difi.correlationId}i"
  servlet:
    context-path: /eidas-cidp-proxy

spring:
  resources:
    cache:
      cachecontrol:
        max-age: 31536000
  error:
    whitelabel:
      enabled: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

messages:
  cache:
    seconds: "-1"

## Generic application config
auditlog:
  dataSeparator: '|'
  dir: c:\var\log\eidas-proxy
  file: audit.log

client:
  id: IdpProxy
dsf:
  gateway:
    retryCount: 1
    timeout: 5000
    url: http://eid-vag-admin:10009/dsf-gateway
eidas-node:
  url: http://localhost/EidasNode/ServiceProvider
eventlog:
  jms:
    queuename: q
    url: tcp://localhost:9999
fileconfig:
  countriesAttributes: /etc/opt/eidas-sidp-proxy/countriesAttributes.json
  readPeriod: 60000
idporten:
  keystore:
    alias: selfsigned
    location: idPortenKeystore.jks
    password: password
    privatekeyPassword: password
    type: jks
mf:
  gateway:
    retryCount: 1
    timeout: 5000
    url: http://localhost/mf-gateway
saml:
  idp:
    entityName: eidas-proxy-idp
  instantIssueTimeSkew: 2
  instantIssueTimeToLive: 10000000
sidp-proxy:
  url: http://eid-vag-opensso.difi.local:10008/eidas-sidp-proxy/
users:
  test: CE/NO/05061989.UTENLANDSK_IDENTIFIKASJONS_NUMMER:05068907693

message:
  path:
